<a href="https://colab.research.google.com/github/Stelath/pytorch-learning/blob/main/Pytorch_Learning_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

x = torch.Tensor([5,3])
y = torch.Tensor([2,1])

print(x*y)

tensor([10.,  3.])


In [ ]:
x =  torch.zeros([2,5])
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [ ]:
y = torch.rand(5, 3)
print(y)

tensor([[7.9588e-02, 2.1696e-05, 7.3089e-01],
        [6.4548e-01, 1.4930e-01, 8.3079e-01],
        [8.8435e-01, 2.6870e-01, 8.1636e-02],
        [6.2235e-01, 3.0117e-01, 3.3232e-01],
        [5.8596e-01, 7.7676e-01, 7.2942e-01]])


In [ ]:
y = y.view([1, 15])
print(y)

tensor([[7.9588e-02, 2.1696e-05, 7.3089e-01, 6.4548e-01, 1.4930e-01, 8.3079e-01,
         8.8435e-01, 2.6870e-01, 8.1636e-02, 6.2235e-01, 3.0117e-01, 3.3232e-01,
         5.8596e-01, 7.7676e-01, 7.2942e-01]])
